/// <reference path="scripts/jaydata.d.ts" />

/*//////////////////////////////////////////////////////////////////////////////////////
////// Autogenerated by JaySvcUtil.exe http://JayData.org for more info        /////////
//////                      oData  V3  TypeScript                              /////////
//////////////////////////////////////////////////////////////////////////////////////*/

// This file is for intelliscene only.

interface IPromise<T> extends Object {
    then: {
        (handler: (args: T) => void): IPromise<any>;
        (handler: (args: T) => any): IPromise<any>;
    };
    fail: {
        (handler: (args: T) => void): IPromise<any>;
        (handler: (args: T) => any): IPromise<any>;
    };
    valueOf(): Object;
} 

declare module JayDataContextSample.Model {
  export class Customer extends $data.Entity {
    constructor();
    constructor(initData: { Id?: number; FirstName?: string; LastName?: string; });
    Id: number;
    FirstName: string;
    LastName: string;
    Description: string;
  }
  
  export class AppContext extends $data.EntityContext {
    onReady(): $data.IPromise<any>;
    onReady(handler: (context: AppContext) => void): $data.IPromise<any>;
    
    Customers: $data.EntitySet<JayDataContextSample.Model.Customer>;
    
  }

}
